---
title: "Methylation classification report"
date: "`r BiocStyle::doc_date()`"
output: BiocStyle::html_document
fig_width: 6
fig_height: 5
vignette: >
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r message=FALSE, warning=FALSE}
library(sesame)
library(askme)
library(dplyr)
```

```{r}
sesame_checkVersion()
```

# Cancer classification

```{r message=FALSE}
sdf = openSesame("~/zhou_lab/projects/20230125_nonGEO_IDATs/EPICv2/207107850105_R01C01", func=NULL)
betas = getBetas(sdf, collapseToPfx=TRUE, mask=FALSE)
askme_cancertype(betas, model=m_cancertype_CNS65)
```

# Copy number variation

```{r}
sdfs.normal = openSesame("~/repo/InfiniumTestIDATs/EPICv2/MaleBlood", func=NULL)
names(sdfs.normal) # Reference is male blood, female samples will have extra X and lower Y
seg = cnSegmentation(sdf, sdfs.normal = sdfs.normal)
visualizeSegments(seg)
```

# MGMT methylation

```{r fig_width=5, fig_height=3, message=FALSE}
betas = getBetas(sdf, mask=TRUE)
visualizeGene(gene_name="MGMT", upstream=30000, dwstream=-260000, betas=na.omit(betas), show.probeNames=FALSE)
```

```{r}
sessionInfo()
```

